[Feature/12] 즐겨찾는 경로가 있는 화면
TEAM-ALOM/finiens-iOS pull request #15
Opened 2023-07-15 01:41 UTC by KimHwiSeon

즐겨찾는 경로가 있는 화면 첫 Pr 입니다. 기본적인 화면은 구성을 완료하였는데, 스와이프 시에 수정이랑 삭제버튼 부분이 아직 완벽하게 구현이 되지 않았습니다. 스크롤 시에 글자만 옆으로 밀리는 느낌이라서 이 부분은 조금 더 공부하고 찾아봐서 추가할 수 있도록 하겠습니다.

2023-07-19 13:13 UTC, mooyoung2309 requested changes
그런데 문제가 하나 보여, 서브 모듈이 들어갔는데 이것좀 지워주고다시 커밋 푸시를 해줘. 아마도 .git 폴더가 여러개 있을거야. 구글링 ㄱㄱ

2023-07-19 13:13 UTC, mooyoung2309 commented on antenna/MyCard.swift
> +                                Image(systemName: "circle.fill")
p2;

오버레이로 너무 많은 뷰들이 보여지고 있는데, 이렇게 하면 문제가 발생해, overlay를 안쓰는 방향으로 다시 한번 짜볼수 있을 것 같은데 어떻게 생각해 ? 그리고 pr 올릴때 스크린샷 캡쳐 부탁해 .. !! 시뮬레이터 스크린샷 해서 올릴수있으니깐 찾아봐 !

2023-07-19 13:13 UTC, mooyoung2309 commented on antenna/Total.swift
> +
p2;

연습 삼아 만든것이지만, 변수명을 좀 더 자세하게 적으려고 노력하면 도움이 많이 될거야 ! Total만 봐서는 어떤 기능을 하는지 알기 어려워. 변수명 뭐할지 고민하는게 중요하고 시간을 쓸만한 것 같아. 왜냐면 이름은 엄청 중요하니깐.

2023-07-22 14:47 UTC, KimHwiSeon commented on antenna/Total.swift
> +
알겠어!!!

2023-07-22 14:48 UTC, KimHwiSeon commented on antenna/MyCard.swift
> +                                Image(systemName: "circle.fill")
이게 아마 rectangle 안에 글자를 넣으려고 overlay을 사용하였는데, ZStack을 활용해서도 할 수 있더라고 그렇게 해서 수정하는 방향으로 다시 해볼게! 그리고 pr 올릴 때 스크린 캡쳐도 해서 올려볼게

2023-07-22 15:31 UTC, closed without merging