Feat/14: 에러 해결 중간 커밋
TEAM-ALOM/finiens-iOS pull request #17
Opened 2023-07-19 11:46 UTC by thissound22

2023-07-19 13:04 UTC, mooyoung2309 requested changes
일단 이렇게 하면 머지를 막는다는 뜻에 Request changes 가 있는데, 로컬에서 계속 커밋 하다가 push 해주면 나한테 다시 노티가 오고 그때 다시 코드리뷰를 해줄수있어. 

우선 버그를 찾는 방법은 여러가지가 있겠지만, 에러메세지를 잘 해석해보려 노력하는게 좋아. 그리고 그냥 gpt에 넣고 에러를 찾아달라 하는 것도 좋은방법이라고 생각해. 나는 잘 안되면 그냥 일단 gpt한테 넣고 그다음에 생각하는 편이야

2023-07-19 13:04 UTC, mooyoung2309 commented on antenna/View/Map/MapStore.swift
> +    struct State: Equatable {
왜 에러가 났었나면, Protocol 키워드를 검색해보면 좋아요. 특히 프로토콜을 상속시킨다면, 꼭 구현해야하는 것을 강제할 수 있습니다. ReducerProtocol은 State와 Action, reducer 함수가 필수적으로 구현되어야 해서 오류가 난것입니다.

2023-07-19 13:04 UTC, mooyoung2309 commented on antenna/View/Map/MapView.swift
> +                        reducer: MapStore()
initialState에 state를 생성자로 주입시켜줘야할것같아보여. MapStore.State() 이런식으로 ?

2023-07-19 13:04 UTC, mooyoung2309 commented on antenna/View/Map/MapStore.swift
> +    }
p1;

변수명은 소문자 출발인 카멜케이스를 사용하는게 좋아 !

2023-07-19 13:06 UTC, mooyoung2309 commented
그리고 브랜치 만들때 feat/#14 이런식으로 #을 붙여줘. 깃허브에서 #의 의미는 이슈랑 pr을 클릭으로 눌러서 접근가능해서 feat/#14 이런식으로 나중에 브랜치가 만들어지면 #14 이부분만 눌러서 14번 이슈로 들어갈수있어.

2023-07-20 06:00 UTC, thissound22 commented
확인했습니다! 수정할게요!!

2023-07-24 12:05 UTC, closed without merging

2023-07-24 12:08 UTC, thissound22 commented
헉...!! 닫은 pr 브랜치에서 수정했더니 이렇게 뜨네요ㅠㅠㅠㅠㅠㅠ.... 죄송합니다.......

2023-07-24 12:09 UTC, thissound22 commented
new pr이 안 뜨길래 여러 번 커밋한 거여서 다 같은 내용입니다...!!! 브랜치 옮기겠습니다...!!