지도 표시, 확대/축소버튼 구현, 출발지/도착지 swap 구현
TEAM-ALOM/finiens-iOS pull request #39
Opened 2023-08-15 08:58 UTC by thissound22

## PR 요약

Simulator Screen Recording - iPhone 14 Pro - 2023-08-15 at 17.56.19.mp4

1. bundle id 변경, client id 추가, info key 추가하여 네이버 지도 api spm 세팅 최종 마무리하였습니다.
2. 확대/축소 버튼 탭 시, 지도 화면이 0.6씩 확대/축소 되도록 하였습니다.
3. 위아래 화살표 버튼 탭 시, 출발지와 도착지가 스왑되도록 하였습니다.

#### 📌 변경 사항

##### ✅ PR check list

1. SearchBar 내부에 DepArrBar를 생성하였습니다. SearchMapView가 무거워 보여서 기존의 DepartureSearchBar와 ArrivalSearchBar를 한 데 모은 것인데, DepArrBar 내부를 보니 또 너무 가벼워 보이기도 합니다. 어느 정도까지 쪼개고 어느 정도까지 큰 몸집을 유지하도록 하는 것이 좋은지 모르겠습니다. 

#### Linked Issue

close #38

2023-08-17 06:53 UTC, mooyoung2309 requested changes
고생하셨습니다! 리뷰가 좀 많네요..! 얼른 고치고 리뷰어 다시 등록해주시면 그때 다시 리뷰해드리겠습니다

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/DepArrBar.swift
> +                DepartureSearchBar(departure: $departure)
p2;

아마도, view를 분리하고는 싶고, store와 엮이게는 하고 싶은것 처럼보여요! 

우선 이런식으로 분리하는 것에 대한 장점을 소개드리자면, 모든 곳에서 DepArrBar을 사용할 수 있습니다. 특히 하지만, 상태값을 내부 변수로서 가지고 있기 때문에 외부에서 상태값에 접근하기 어려운 경우가 있어보이네요. 컨셉자체는 나쁘지 않아보입니다. 

단점은 너무 많은 재사용성을 고려했기 때문에 독립적인 View가 되었다는 단점이 있습니다. 이렇게 되면 TCA 구조로 녹여내기 위해서 ViewStore와 내부의 State 변수들을 연결해주어야하는 상황이 발생해보입니다. 따라서 

https://github.com/depromeet/Pumping-iOS/blob/develop/Projects/Feature/Workout/Interface/Sources/End/WorkoutEndView.swift

위의 상황처럼 내부의 함수로 빼내서 viewStore의 강한 결합을 주는 방법도 추천드려요. 이렇게되면 단점은 해당 SearchMapView에서만 사용가능하다는 단점이 있습니다.

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/DepArrBar.swift
> +        .frame(width: 353, height: 104)
p4;

너비값을 줄때 하드코딩인지 아닌지 고민해보면 좋을것같아요!

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/SearchBar.swift
> +                    Image(systemName: "magnifyingglass")
p5;

tuist를 활용해서 swiftui의 이미지를 사용하는 방법에 대해 구글링해보면 좋을것같아요. 저는 처음에 신세계였습니다.

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchMapView.swift
> +
p2;

해당 뷰는 전역적으로 사용될만한 지도 뷰인것같아서 디자인시스템으로 파일을 옮기는 것을 추천드려요!

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchMapView.swift
> +                            }
p1;

제가 말한 부분이 이부분인데요, 아마도 이런 고민을 하셨을 것 같아요. 부모의 줌 버튼이 눌리는 상태를 자식한테 어떻게 전달하지? 하는 고민을 해보다가 노티피케이션 센터를 사용하였을텐데, 이런 노티피케이션 사용은 지양해야하고, 가독성과 성능을 저하시킬 수 있습니다.

UIMapView의 zoomLevel을 부모에서 내려주는 방식을 추천드리는데, Binding에 대해 검색해보면 좋을것같습니다.

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchMapView.swift
> +                            }
p1;

같은 사항입니다.

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchMapView.swift
> +    @State private var isScrollGestureEnabled = true
p2;

하나의 파일에 여러개의 View들이 있네요. 논리적으로 잘 설명할 수 있을정도로 필요성이 명확하게 겹쳐서 같은 파일에 넣는 것 까지는 허용이지만, 그게 아니라면 파일을 분리하는것이 마음 편해요!

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchMapView.swift
>      }
p4;

이부분은 델리게이트 때문인가요? 

코디네이터로 작성한 이유가 궁금합니다!

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/SearchBar.swift
> +                }
p5;

```\.``` 이렇게 접근하는 방식은 뭔가요? 설명이 가능할까요?

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/SearchBar.swift
> +                        viewStore.send(.isTappedLocationSearchBar)
p3;

store action의 행위자 주체가 아닌 수동형으로 쓰여있어보이네요. is 키워드는 bool을 리턴하는 것을 의미합니다. 따라서 tapLocationSearchBar 정도가 적당해보이네요!

2023-08-17 06:53 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/SearchBar.swift
> +                        viewStore.send(.isTappedLocationSearchBar)
이부분 살짝 취향차이가 있겠네요.. 그래서 action의 이름이 is로 시작하는 것보다는 더 좋게 작성할 수 있어보입니다

2023-08-21 03:16 UTC, thissound22 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/DepArrBar.swift
> +        .frame(width: 353, height: 104)
앗 이 부분 항상 신경쓰였는데 하드 코딩이었네요! 상수로 수정해보겠습니다

2023-08-22 06:03 UTC, thissound22 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/SearchBar.swift
> +                }
\.은 경로를 나타내는 문법으로 객체의 값을 직접 가져오지 않고 간접적으로 불러오는 방식이에요. KeyPath를 사용하지 않고 프로퍼티에 접근하려면 일일이 문자열을 사용해야 해서 오타가 날 가능성이 있기 때문에 런타임 에러를 방지하기 위해 사용돼요. 여기서는 state의 locationSearch 프로퍼티에 접근한다는 뜻으로 쓰였어요.

2023-08-24 12:59 UTC, thissound22 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchMapView.swift
>      }
코디네이터는 외부와 상호작용하기 위해 쓰이는데 UIKit 기능을 SwiftUI 뷰에 통합하는 역할을 합니다. UIKit 기반의 델리게이트를 사용하는 경우에 코디네이터로 작업을 처리할 수 있는데, 여기서는 UIKit을 사용하고 있지 않아서 구현할 필요가 없을 것 같기도 합니다!

2023-08-24 13:51 UTC, mooyoung2309 approved these changes
고생하셨습니다! 회의때 말씀드린 내용 반영하면 될것같아요!

2023-08-24 13:51 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchBar/SearchBar.swift
> +                }
설명감사합니다!

2023-08-24 13:51 UTC, mooyoung2309 commented on Targets/Finiens/Sources/Feature/SearchMap/SearchMapStore.swift
> +        case ScopeButtonTapped
p2;

case는 아주 특별한 경우가 아니면 소문자로 컨벤션을 맞춰주는게 좋습니다.

2023-08-25 02:33 UTC, merged